version: '3'
services:
  booker:
    build: .
    ports:
      - 8080:8080
    environment:
      PORT: 8080
      TZ: America/Winnipeg
      BOOKING_EXPIRY_MINS: 10
      NODE_ENV: development
    env_file:
      - .env
